site_name: Documentación Contador Pádel
site_url: https://contadorpadel.rabid.es
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  logo: assets/raqueta-de-padel-icon.png
  favicon: assets/raqueta-de-padel-icon.png
  language: es
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
nav:
  - Inicio: index.md
  - Configuración Recomendada: setup.md
  - Guía de Inicio Rápido: quickstart.md
  - Opciones del Contador:
    - Opciones de Partido: counter/match.md
    - Selección de Equipos: counter/teams.md
    - Pantalla del Contador: counter/counter.md
  - Ajustes:
    - General: settings/general.md
    - Controles: settings/controls.md
    - Sonidos Extra: settings/custom_sounds.md
  - Ayuda/Informar de un problema: help.md
extra:
  alternate:
    - name: English
      link: https://padelcounter.rabid.es
      lang: en
    - name: Spanish
      link: https://contadorpadel.rabid.es
      lang: es